sudo: required # required for docker
language: go
go:
  - '1.12'
  - master
cache:
  directories:
    - $HOME/gopath/pkg/mod
env:
  - ES_VERSION=5.6.16 ES_OSS_IMAGE=elasticsearch:${ES_VERSION} ES_IMAGE=docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION} ES_COMMAND="elasticsearch -Epath.repo=/tmp"
  - ES_VERSION=6.8.0 ES_OSS_IMAGE=docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION} ES_IMAGE=docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION} ES_OPENDISTRO_IMAGE=amazon/opendistro-for-elasticsearch:0.9.0
  - ES_VERSION=7.0.1 ES_OSS_IMAGE=docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION} ES_IMAGE=docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
matrix:
  allow_failures:
    - go: master
addons:
  ssh_known_hosts: github.com
  apt:
    update: true
    packages:
      - docker-ce
services:
  - docker
before_install:
  - sudo sysctl -w vm.max_map_count=262144
  - docker-compose pull
  - docker-compose up -d
install:
  - export ELASTICSEARCH_URL=http://127.0.0.1:9200
  - export TF_LOG=INFO
  - env GO111MODULE=on go mod vendor
script:
  - export GO111MODULE=on
  - wget -q --waitretry=1 --retry-connrefused --tries=60 --timeout 60 -O - $ELASTICSEARCH_URL
  # Opendistro lazily initializes it's indexes, warm it up here :|
  # https://github.com/opendistro-for-elasticsearch/alerting/issues/60
  - |
    if [ -n "$ES_OPENDISTRO_IMAGE" ]; then
      wget -q --waitretry=1 --retry-connrefused --tries=60 --timeout 60 -O - 127.0.0.1:9220
      curl -X POST -H 'Content-type: application/json'  -d '{"name":"_warmup","type":"slack","slack":{"url": "http://www.example.com"}}' 127.0.0.1:9220/_opendistro/_alerting/destinations
    fi
  # enforce formatting
  - FILES_TO_FMT=$(gofmt -l .); [ -z "$FILES_TO_FMT" ] || (echo "$FILES_TO_FMT"; exit $?)
  # run tests
  - TF_ACC=1 go test -v -cover
before_deploy:
  - export GO111MODULE=on
  - go get github.com/mitchellh/gox
  - export TARGET_OS="freebsd darwin linux windows"
  - export TARGET_ARCH="386 amd64"
  # Use terraform provider conventions
  #  https://www.terraform.io/docs/configuration/providers.html#third-party-plugins
  - export FILE_NAME="terraform-provider-elasticsearch_${TRAVIS_TAG}_{{.OS}}_{{.Arch}}"
  - gox -os "$TARGET_OS" -arch "$TARGET_ARCH" -output="$FILE_NAME"
  - CGO_ENABLED=0 gox -os "$TARGET_OS" -arch "$TARGET_ARCH" -output="${FILE_NAME}_static"
deploy:
  provider: releases
  api_key:
    secure: "WNhQQmCwWepKTEax7DthbABeqTkKRGJyEkKGjWNFS45dZARWKwslYG4vKK2IUyQpcYK+1Bx0s/guqACzE9tFIuDu2DnhgdROfF1i61Ml1zqepEbdytPGnlrLDPA8XVI9WwBpef8HpjkoLhRlpkmU7DjcBf743CnzDXUyL85/KD8E9uaIV8Crf8efRnU37gXz64AXHUyLRkmyASuX62HSwg33OMUyxhtuYonSiLhWuEgIJHyAZKFCLtO9sd4WzwkfSK+x+GR29cg/1iEoJSLgUDHwJS4kRGbWdgbROfrtuHWL0/tph5jMislXdcrlp1A7raj3U1HLZRkFDHDWJVeis0iGlw/P7v1k7TEwUbx2izt7D+yZXmN9yHOcjJNjoZdwlSGoRXbiQOinOB7iJ2erHhSSx/Xwv/iXGTevPXEkcWh3GeFh6S0e//7nnO/n1NMIBl9yhxqBNq5KefE2Xk1ChNKjTmvGRUU7+na+yq27ifTy+4dm2Vn22MCyJhBrisxqPPmyTYwS2Ajkz7cPZ9jT0gUqlET8fUsijbCn5XIpE+f2rH0vLElApEB3JvaFhHa4x3/AKhNb/nFj2gFzvZQt/UuS+5DFR75qO5jwM3MMQ9t/KJJ/2P7uL+9+LHlE+6Y5kETT5orhlVtB1l7GTnYyEZSbS1ZWufvcuKNQ8ONzPo4="
  file: terraform-provider-elasticsearch*
  skip_cleanup: true
  file_glob: true
  on:
    tags: true
    branch: master
    go: '1.12'
